
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjkxMzkxMTEx","is_bot":false,"login":"jamespflaging","name":"James Pflaging"},"headRefName":"James-navbarpages","number":96,"title":"James Nav Bar, Pages, Stories, Tests, Updates to Old tests","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/pull/96"},{"author":{"id":"U_kgDOBbk9KA","is_bot":false,"login":"owenjpark","name":"Owen Park"},"headRefName":"Owen-UCSBDiningCommonsMenuItem-pages","number":84,"title":"OP - Copy Placeholders for UCSBDiningCommonsMenuItem pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/pull/84"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-menuitemreview-placeholders","number":82,"title":"zp - added MenuItemReview placeholder components","url":"https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/pull/82"}]
